# Generated by Django 5.0.6 on 2024-07-05 10:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_college',
            new_name='College',
        ),
        migrations.RenameModel(
            old_name='tbl_courses',
            new_name='Courses',
        ),
        migrations.RenameModel(
            old_name='tbl_personal',
            new_name='Personal',
        ),
        migrations.RenameModel(
            old_name='tbl_work_experience',
            new_name='Work_experience',
        ),
    ]
